services:
  - type: web
    name: harly-host-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ACCOUNT_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
